# Generated by Django 4.0.4 on 2022-04-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='languague_name',
            new_name='language_name',
        ),
    ]
