# Generated by Django 4.2.1 on 2023-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0003_alter_user_bio_alter_user_favorite_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
