# Generated by Django 4.0.4 on 2022-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0003_category_alter_word_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
