# Generated by Django 4.0.4 on 2022-04-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0004_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
