# Generated by Django 4.2.1 on 2023-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
