# Generated by Django 4.2.1 on 2023-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0008_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='languageschool.badge'),
        ),
    ]
