# Generated by Django 4.0.4 on 2022-04-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0010_alter_word_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='article_name',
        ),
    ]
