# Generated by Django 4.2.1 on 2023-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
