# Generated by Django 4.0.4 on 2022-04-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0012_rename_synonims_word_synonym_word_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='word_name',
        ),
    ]
