# Generated by Django 4.0.4 on 2022-05-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0015_alter_language_personal_pronoun_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meaning',
        ),
    ]
