# Generated by Django 4.0.4 on 2022-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0017_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%d/%m/%Y'),
        ),
    ]
