# Generated by Django 4.0.4 on 2022-05-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0020_appuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='synonym',
            new_name='synonyms',
        ),
    ]
