# Generated by Django 4.0.4 on 2022-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0021_rename_synonym_word_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
