# Generated by Django 4.0.4 on 2022-11-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0029_game_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_tag',
        ),
    ]
