# Generated by Django 4.0.4 on 2022-12-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0032_alter_appuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('article_name', 'language'), name='article_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='conjugation',
            constraint=models.UniqueConstraint(fields=('word', 'tense'), name='conjugation_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('user', 'language', 'game'), name='score_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word_name', 'language', 'article'), name='word_unique_constraint'),
        ),
    ]
