# Generated by Django 4.0.4 on 2023-01-02 21:57

from django.db import migrations, models
import languageschool.models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0036_alter_appuser_picture_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag_image',
            field=models.ImageField(upload_to=languageschool.models.get_upload_to),
        ),
    ]
