# Generated by Django 4.0.4 on 2023-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0038_alter_language_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favorite_words',
            field=models.ManyToManyField(to='languageschool.word'),
        ),
    ]
