# Generated by Django 4.0.4 on 2023-04-18 09:34

from django.db import migrations, models
import languageschool.models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0039_appuser_favorite_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to=languageschool.models.get_upload_to),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
