# Generated by Django 4.0.4 on 2023-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0040_game_image_game_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='setup_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
