# Generated by Django 4.0.4 on 2023-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0041_game_setup_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='setup_link',
            new_name='link',
        ),
    ]
