# Generated by Django 4.0.4 on 2023-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0042_rename_setup_link_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='android_game_activity',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
