# Generated by Django 4.0.4 on 2023-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0044_gameround'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='game_round_unique_constraint'),
        ),
    ]
