# Generated by Django 4.2.1 on 2023-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0045_gameround_game_round_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
