# Generated by Django 4.2.1 on 2023-05-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageschool', '0046_appuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='bio',
        ),
    ]
